title: Yiyi Liu's Homepage
page-top-title: Yiyi Liu's Homepage
top-section-bg-text: Muse Dash, MDCP and Maimai
home-subtitle: 刘懿逸, Yiyi Liu
copyright-text: '&copy; Yiyi Liu 2020-2025. All Rights Reserved.'
